FROM redhat/ubi9:9.3

WORKDIR /root

# install jdk8
RUN apt-get update && \
    apt install -y openjdk-8-jdk 

# install hive metastore
RUN wget https://mirrors.sonic.net/apache/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz && \
    tar -xzvf apache-hive-3.1.3-bin.tar.gz && \
    mv apache-hive-3.1.3-bin /opt/hive


# set environment variable
ENV HIVE_HOME=/opt/hive
ENV HADOOP_HOME=/opt/hadoop
ENV HIVE_CONF_DIR=/opt/hive/conf
ENV PATH=$PATH:$HIVE_HOME/bin

# install postgresql
RUN apt install postgresql postgresql-contrib && \
    wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar && \
    mv postgresql-42.5.4.jar ${HIVE_HOME}/lib

# copy config vào thư mục tmp của container
COPY config/* /tmp/config/

# chuyển file config
RUN mv /tmp/config/* ${HIVE_HOME}/conf/

# init schema
RUN {HIVE_HOME}/bin/schematool -dbType postgres -initSchema

# start hive metastore
CMD [ "$HIVE_HOME/bin/hive --service metastore" ]


